using System;
using System.Collections.Generic;
using BZCommon.Helpers;

namespace RuntimeHelperZero
{
    public partial class RuntimeHelperZero
    {
        public List<TechTypeData> techTypeDatas = new List<TechTypeData>();

        public void InitFullTechTypeList(ref List<TechTypeData> TechTypeList)
        {
            int[] techTypeArray = (int[])Enum.GetValues(typeof(TechType));

            for (int i = 0; i < techTypeArray.Length; ++i)
            {
                TechType techType = (TechType)techTypeArray[i];

                if (TechType_Blacklist.Contains(techType))
                    continue;

                string name = Language.main.Get(TechTypeExtensions.AsString((TechType)techTypeArray[i], false));

                TechTypeList.Add(new TechTypeData(techType, name));
            }

            TechTypeList.Sort();
        }

        public static readonly List<TechType> TechType_Blacklist = new List<TechType>
        {             
            TechType.Hoopfish,
            TechType.HoopfishSchool,
            TechType.AcidOld,
            TechType.Databox,
            TechType.BaseDoor,
            TechType.None,            
            TechType.AnalysisTreeOld,
            TechType.AquariumBlueprint,            
            TechType.BarnacleSuckers,
            TechType.BaseBulkheadBlueprint,
            TechType.BaseMapRoomBlueprint,
            TechType.BaseObservatoryBlueprint,
            TechType.BasePlanterBlueprint,
            TechType.BaseRoomBlueprint,
            TechType.BaseUpgradeConsoleBlueprint,
            TechType.BaseWaterParkBlueprint,
            TechType.BatteryChargerBlueprint,
            TechType.BenchBlueprint,
            TechType.BikemanHullPlateBlueprintOld,
            TechType.BioreactorBlueprint,            
            TechType.Bladderfish,
            TechType.BladderfishAnalysis,            
            TechType.Boomerang,
            TechType.BoomerangAnalysis,
            TechType.BrainCoral,            
            TechType.CalciteOld,
            TechType.CarbonOld,            
            TechType.ConstructorBlueprint,
            TechType.CookedBladderfish,
            TechType.CookedBoomerang,            
            TechType.CookedHoopfish,            
            TechType.CookedSpinefish,
            TechType.CoralOldPlaceholder,
            TechType.CountOld,
            TechType.CoveTree,            
            TechType.Crash,
            TechType.CrashedShip,
            TechType.Creepvine,
            TechType.CreepvinePiece,
            TechType.CreepvineSeedCluster,
            TechType.CuredBladderfish,
            TechType.CuredBoomerang,           
            TechType.CuredHoopfish,            
            TechType.CuredSpinefish,
            TechType.CurrentGenerator,
            TechType.CutefishEggUndiscovered,
            TechType.CyclopsBlueprint,
            TechType.CyclopsBridgeBlueprint,
            TechType.CyclopsDockingBayBlueprint,
            TechType.CyclopsEngineBlueprint,
            TechType.CyclopsHullBlueprint,
            TechType.DevTestItemBlueprintOld,
            TechType.Drill,
            TechType.ExosuitBlueprint,
            TechType.EyesPlant,
            TechType.FabricatorBlueprintOld,
            TechType.FarmingTrayBlueprint,
            TechType.FernPalm,
            TechType.FiltrationMachineBlueprint,
            TechType.FlintOld,
            TechType.FragmentAnalyzerBlueprintOld,            
            TechType.GenericEgg,            
            TechType.Grabcrab,            
            TechType.HangingFruitTree,
            TechType.HangingStinger,
            TechType.HeatArea,            
            TechType.HoleFishAnalysis,
            TechType.Hoopfish,
            TechType.HoopfishAnalysis,
            TechType.HoopfishSchool,            
            TechType.HugeSkeleton,
            TechType.JellyPlant,
            TechType.JellyPlantSeed,           
            TechType.LavaZoneEgg,
            TechType.LEDLightBlueprint,
            TechType.LockerBlueprint,
            TechType.MedicalCabinetBlueprint,            
            TechType.Melon,
            TechType.MelonPlant,
            TechType.MelonSeed,            
            TechType.MembraneOld,            
            TechType.MonsterSkeleton,
            TechType.MoonpoolBlueprint,            
            TechType.NuclearReactorBlueprint,
            TechType.ObservatoryOld,            
            TechType.OrangePetalsPlant,           
            TechType.PictureFrameBlueprint,
            TechType.PinkFlower,            
            TechType.PlanterBoxBlueprint,
            TechType.PlanterPot2Blueprint,
            TechType.PlanterPot3Blueprint,
            TechType.PlanterPotBlueprint,
            TechType.PlanterShelfBlueprint,
            TechType.Player,
            TechType.PowerCellChargerBlueprint,            
            TechType.PowerTransmitterBlueprint,            
            TechType.PrecursorIonEnergyBlueprint,
            TechType.PrecursorLostRiverLabEgg,            
            TechType.PropulsionCannonBlueprint,            
            TechType.PurpleBranches,            
            TechType.PurpleStalk,
            TechType.PurpleStalkSeed,
            TechType.PurpleTentacle,            
            TechType.PurpleVegetable,
            TechType.PurpleVegetablePlant,           
            TechType.RadiationSuitBlueprint,
            TechType.RadioBlueprint,            
            TechType.ReaperSkeleton,
            TechType.RedBasketPlant,           
            TechType.RedBush,
            TechType.RedBushSeed,           
            TechType.RedGreenTentacle,            
            TechType.ReefbackAdvancedStructure,            
            TechType.ReefbackDNA,            
            TechType.ReefbackShell,
            TechType.ReefbackTissue,           
            TechType.ReinforcedDiveSuitBlueprint,
            TechType.ReinforceHullBlueprint,            
            TechType.RocketBaseLadder,           
            TechType.Rockgrub,
            TechType.RockPuncher,            
            TechType.ScannerRoomBlueprint,            
            TechType.SeaDragonSkeleton,            
            TechType.SeaEmperorJuvenile,
            TechType.SeaEmperorLeviathan,
            TechType.SeaglideBlueprint,
            TechType.SeamothBlueprint,           
            TechType.ShockerEgg,
            TechType.ShockerEggUndiscovered,            
            TechType.SignBlueprint,
            TechType.Skyray,
            TechType.SkyrayNonRoosting,            
            TechType.SmallMelon,            
            TechType.SolarPanelBlueprint,            
            TechType.SpecialHullPlateBlueprintOld,
            TechType.SpecimenAnalyzerBlueprint,
            TechType.Spinefish,
            TechType.SpinefishAnalysis,
            TechType.SpotlightBlueprint,
            TechType.SpottedLeavesPlant,            
            TechType.StarshipCargoCrateBlueprint,
            TechType.StarshipChairBlueprint,
            TechType.StarshipCircuitBoxBlueprint,
            TechType.StarshipDeskBlueprint,
            TechType.StarshipMonitorBlueprint,
            TechType.StasisRifleBlueprint,
            TechType.StillsuitBlueprint,
            TechType.TechlightBlueprint,
            TechType.TerraformerBlueprint,
            TechType.ThermalPlantBlueprint,
            TechType.TransfuserBlueprint,
            TechType.TreeMushroomPiece,            
            TechType.WorkbenchBlueprint,
            TechType.PrecursorLostRiverProductionLine,            
            TechType.BaseCorridor,
            TechType.BaseFoundation,
            TechType.AminoAcids,
            TechType.NuclearReactorFragment,
            TechType.BaseNuclearReactorFragment,            
            TechType.BatteryAcidOld,            
            TechType.StasisSphere,
            TechType.PrecursorLostRiverWarperParts,            
            TechType.BioreactorFragment,
            TechType.PrecursorLostRiverLabBones,
            TechType.DiveSuit,
            TechType.StillsuitFragment,
            TechType.CombustibleOld,            
            TechType.DolomiteOld,
            TechType.EatMyDictionHullPlateBlueprintOld,            
            TechType.EmeryOld,
            TechType.PowerCellChargerFragment,
            TechType.PrecursorEnergyCore,
            TechType.EnvironmentPlaceholder,            
            TechType.BuildBot,
            TechType.BuilderFragment,            
            TechType.EthanolOld,
            TechType.EthyleneOld,            
            TechType.BaseWall,            
            TechType.LootSensorMetal,           
            TechType.TreeMushroom,
            TechType.Graphene,
            TechType.GravSphereFragment,            
            TechType.BlueCoralTubes,
            TechType.Placeholder,
            TechType.ThermalPlantFragment,            
            TechType.ConstructorFragment,
            TechType.FloatingStone,
            TechType.HydrogenOld,
            TechType.BaseCorridorI,
            TechType.BaseCorridorGlassI,            
            TechType.PrecursorTeleporter,
            TechType.PrecursorThermalPlant,
            TechType.BaseMapRoom,            
            TechType.Sign,

            //*** Newly checked types            
            TechType.PrecursorNPCBody,
            TechType.BaseWaterPark,            
            TechType.BlueAmoeba,
            TechType.Anomaly,            
            TechType.PrecursorSanctuaryCube,
            TechType.BaseGlassDomeFragment,
            TechType.BaseLargeRoomFragment,
            TechType.BaseRechargePlatform,            
            TechType.BaseBioReactor,            
            TechType.BloodRoot,            
            TechType.BlueJeweledDisk,
            TechType.Boulder,
            TechType.BlueLostRiverLilly,            
            TechType.BaseBulkhead,            
            TechType.CalciumChunk,            
            TechType.BaseControlRoom,
            TechType.BlueTipLostRiverPlant,
            TechType.DrillableSulphur,            
            TechType.ResearchBaseExo,
            TechType.DataChip,            
            TechType.DiveHatch,
            TechType.Enamel,
            TechType.EscapePod,
            TechType.ExosuitThermalReactorModuleFragment,
            TechType.Fiber,
#pragma warning disable CS0612 // Type or member is obsolete
            TechType.Cyclops
#pragma warning restore CS0612 // Type or member is obsolete
        };
    }
}
